apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: taxcalc-dev
resources:
  - ../../base
images:
  - name: uptimecrew/taxcalc-api
    newName: 043000359802.dkr.ecr.us-east-1.amazonaws.com/uptimecrew/taxcalc-api_sai
    newTag: 37f63b8a3456abc3532086474abf53b0c55dd672
replicas:
  - name: taxcalc-api
    count: 1
patches:
  - path: patch-configmap.yaml
  - path: patch-ingress.yaml
  - path: patch-hpa.yaml
  - path: patch-kafka.yaml
