# Keep app.kubernetes.io/version aligned with taxcalc-agent-svc images.newTag in this overlay.
apiVersion: apps/v1
kind: Deployment
metadata:
  name: taxcalc-agent-svc
spec:
  template:
    metadata:
      labels:
        app.kubernetes.io/version: cfcd5ef595ce1af052b662554064b7762dbadf51-arm64
