apiVersion: v1
kind: ConfigMap
metadata:
  name: taxcalc-api-config
data:
  SPRING_PROFILES_ACTIVE: dev
  LOGGING_LEVEL_ROOT: DEBUG
  SPRING_DATASOURCE_URL: jdbc:postgresql://postgres.taxcalc-dev.svc.cluster.local:5432/taxcalc_dev
  SPRING_DATA_MONGODB_URI: mongodb://mongo.taxcalc-dev.svc.cluster.local:27017/taxcalc
  SPRING_DATA_REDIS_HOST: redis.taxcalc-dev.svc.cluster.local
  SPRING_KAFKA_BOOTSTRAP_SERVERS: kafka.taxcalc-dev.svc.cluster.local:9092
  OTEL_EXPORTER_OTLP_ENDPOINT: http://otelcol.taxcalc-dev.svc.cluster.local:4317
