# Keep app.kubernetes.io/version aligned with taxcalc-agent-svc images.newTag in this overlay.
apiVersion: apps/v1
kind: Deployment
metadata:
  name: taxcalc-agent-svc
spec:
  template:
    metadata:
      labels:
        app.kubernetes.io/version: 69edc02abf8b4c234ddf95e3d3092a0eb0f87208-arm64
